### ISSUE TITLE
Invalid generated address.json prior test coverage

### ISSUE THREAD

**Issue by 0x3bfc** [oceanprotocol/contracts#248]
## Problem description
The `address.json` file is maintained by the deployment script (truffle migration script). It is automatically updated prior the deployment for the supported testnet(s) and the mainnet.  

If you try to run `npm run test:cover` it will update the `address.json` file but referring the created contracts address under `undefined` network.
```json
...
"undefined": {
    "DTFactory": "0x....",
    "BFactory": "0x....",
    "FixedRateExchange": "0x...",
    "Metadata": "0x...",
    "Ocean": "0x..."
  }
...
```

**Comment by alexcos20** [comment]
postponed for V4
