### ISSUE TITLE
Adding a smartcontract that can bundle multiple actions (createDT, publishDDO) in one call

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/contracts#249]

**Comment by trentmc** [comment]
The main motivation for this was to reduce gas fees (1). A secondary motivation was reducing # txs to confirm (2).

(1) was solved via the recent release to polygon. (2) may have been done, and if not, it's not a priority in light of V4-ish work that will change around smart contracts in several ways.

Therefore, closing.
