### ISSUE TITLE
Enable Etherscan to show up the pool share tokens decimals

### ISSUE THREAD

**Issue by 0x3bfc** [oceanprotocol/contracts#253]
by @kremalicious 
Is there a way to do the same for the pool share tokens? Like this one https://etherscan.io/token/0xf55ba2b65a6f12906920f6c3964d95cd0d4f8dfc
in a transaction spending pool shares and receiving OCEAN https://etherscan.io/tx/0xa0d2ccc6068cde383fef3659640c4c1f5f6c3b30c25b194d3a0341a5e3e1ad5a

--
Comment by @trentmc 
- Users are seeing this as a bug, because it looks like they have insane balances (when it's really just the wei). 
- That may point to lower level bugs too. 
- Therefore adding 'bug' label to this issue

**Comment by kremalicious** [comment]
right, so all good for the datatoken contracts. What I also meant was the balancer pool tokens, which right now have a verified contract but their `decimals` is `0`. Like on here, fresh pool 
https://etherscan.io/address/0x43115b5aD3CB6318e24fa815Fe13e4988ECe8D5C#readContract

And I think this is also the pool token:
https://etherscan.io/token/0x43115b5ad3cb6318e24fa815fe13e4988ece8d5c

I'm sure we can't verify each and every pool token contract, but probably their factory? Any other way?

All the pool tokens continue to show up in all tools in wei: 

![IMG_4BCBA2C7CF86-1](https://user-images.githubusercontent.com/90316/97792382-b72f8800-1bdd-11eb-9289-13a464ebee3e.jpeg)

**Comment by alexcos20** [comment]
postponed for V4
