### ISSUE TITLE
Tokens stuck in old contract

### ISSUE THREAD

**Issue by shahbazn** [oceanprotocol/contracts#267]
**Describe the bug**
Hello Folks. It seems some of the ocean tokens I was holding were not automatically transferred to the new contract. My address is 0x96210908DF6cb96028833189DA232d47df9C7658.

It seems to be a bug in the smart contract but I am not sure. Some help here would be highly appreicated :)

**Comment by innoprenuer** [comment]
Hey @shahbazn you are probably using old OCEAN contract. OCEAN contract has been changed and equivalent tokens were transferred to you - https://etherscan.io/token/0x967da4048cD07aB37855c090aAF366e4ce1b9F48?a=0x96210908DF6cb96028833189DA232d47df9C7658 

This is the new token contract. Please use this contract address for transfers.
