### ISSUE TITLE
Rename 'master' -> 'main' branch

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/contracts#274]
**Is your feature request related to a problem? Please describe.**
Most ocean repos have had their `master` branch renamed to `main` recently. 

This one hasn't. We should strive for consistency.

**Describe the solution you'd like**

- [ ] Rename 'master' -> 'main' branch.
- [ ] Check around to make sure other stuff doesn't get broken, and fix accordingly.

**Comment by 0x3bfc** [comment]
@jamiehewitt15 you need a privileged account to do that. I already asked @alexcos20 to complete that task.

**Comment by 0x3bfc** [comment]
This also could help for the renaming procedures  https://www.git-tower.com/learn/git/faq/git-rename-master-to-main/

**Comment by jamiehewitt15** [comment]
Yeah thanks, I also just noticed that while trying to do it. I've removed myself from this

**Comment by 0x3bfc** [comment]
done
