### ISSUE TITLE
Reconcile unit tests in ocean.js & contracts

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/contracts#290]
**Background / motivation**

This is pre-V4 refactoring work.

Both `contracts` and `ocean.js` repo have a lot of JS-based tests. This hurts maintainability: where do you test? Right now it's unclear what the division is, and there's almost certainly a lot of redundancy. This violates DRY (Don't Repeat Yourself) principle, which we strive to follow.

Furthermore, @lacoop6tu mentioned: 
- "have been looking at the tests in contracts and most of them are actually already in the Ocean.js, (some of those tests I added them personally while increasing code coverage weeks ago). I will go test by test to see what is tested in the contracts and not in Ocean.js)"
- "The real difference is that there's a `OPFCommunityFeeCollector.sol` which is not tested in Ocean.js, well there's not even the class for it in the library"

**Scope of issue**

By the time this issue is done:
- There should be _no_ tests in `contracts` repo. (Because each given tests will have been moved to ocean.js / modified, or deprecated).
- Documentation in `contracts` repo should instruct user on tests using ocean.js
- Ideally, CI for `contracts` repo uses ocean.js too (not sure how feasible)
- ocean.js has a support for `OPFCommunityFeeCollector.sol`, and tests too. (This can be expanded upon in "help community monetize" v4 work [multi-repo-issue#47](https://github.com/oceanprotocol/multi-repo-issue/issues/47).)

**Comment by 0x3bfc** [comment]
I totally disagree with this:
- Tests should not be removed even if there are a duplications, I don't care about the DRY, I do care about the code quality, coverage, static analysis and having encapsulated code. For more info, please revisit my repo [here](https://github.com/0x3bfc/Awesome-Smart-Contracts-Notes).
- Ocean.js is a separate repo that might NOT updated with the latest contract `main` branch. It takes time to prove the concepts in ocean js/py and this is not the same for the contract.
- The same for the documentation. please check the best practice below.

Finally, If you want to remove the tests from the contracts repo, simply move this repo to the ocean-js but this will break the modularity and won't work for the ocean.py lib.

Again, please follow the smart contracts best practice (link below).

https://consensys.github.io/smart-contract-best-practices/

**Comment by trentmc** [comment]
We agree on code quality, great.

DRY is all about code quality. Violating DRY --> low quality code.

https://code.tutsplus.com/tutorials/3-key-software-principles-you-must-understand--net-25161

Everything else flows from this.

**Comment by 0x3bfc** [comment]
DRY is already applied within the same repo and **`source code`** in general, not in the tests, because each piece of code needs to be tested before releasing it. If you have a duplicate part(s) in the contracts tests, then group them one/two `test` helper file(s) and use that helper.

>> BTW the Consensys link you shared above agrees: "An ideal smart contract system from a software engineering bias is modular, reuses code instead of duplicating it" link

It talks about the source code not the tests.

Please we need to focus on the right scopes for the DRY, the case here is for different repos. The tests we have in the ocean.js are integration tests. The test in contracts are unit-tests.

**Comment by trentmc** [comment]
Testing code _is_ code. Like all code, it needs to be written according to SW engineering principles, including DRY.

Like any module, ocean.js should have both unit tests and integration tests.

SW engineering principles don't magically go away when considering >1 repo at once.

>  each piece of code needs to be tested before releasing it

Agreed, this is why the description includes "Documentation in contracts repo should instruct user on tests using ocean.js"

**Comment by trentmc** [comment]
AlexC, Andrea and I talked. Here's what we will do: keep test structure as-is. No more work needed here.
