### ISSUE TITLE
Implement EIP-2612 in all datatokens

### ISSUE THREAD

**Issue by TimDaub** [oceanprotocol/contracts#294]
Last week, 9,4% of token transactions on Ethereum were `Approval` transactions [1]. `Approval` transactions in ERC-20 tokens are made to e.g. allow a third-party contract to withdraw tokens from an ERC-20 token. E.g. when a user does a swap on the Ocean Market, most of the time an `Approval` transaction is required.

However, `Approval` transactions' on-chain execution is wasteful and in many cases unnecessary. [ERC-2612 ](https://eips.ethereum.org/EIPS/eip-2612) addresses this problem by allowing to approve messages that are broadcast and signed offline using [ERC-712](https://eips.ethereum.org/EIPS/eip-712). ERC-2612 adds a function to the ERC-20 interface and is hence NOT a breaking change. There are implementations running in production [2].

For the Ocean Market interface there's an additional benefit that too applies for L2:

- Any user interface flow that requires an upfront approval transaction from a user means the user has to do at least two on-chain interactions with Metamask. Generally, more means worse. Don't make me think. But there's also specific reasons like:
  - The user may become insecure/confused about the approval transactions and hence cancel the process
  - The user may become impatient

For all new data tokens that are launched on the Ocean market. Please consider adding EIP-2612, thanks.

## References

- 1: https://duneanalytics.com/queries/35211
- 2: https://github.com/Uniswap/uniswap-v2-core/blob/master/contracts/UniswapV2ERC20.sol

**Comment by TimDaub** [comment]
For completion, I should mention that there's also:

- https://github.com/ethereum/EIPs/issues/677 and
- https://eips.ethereum.org/EIPS/eip-777

that address the same issue. However, ERC-677 isn't a valid canonicalized EIP document and ERC-777 seems dramatically bloated to me. My personal favorite is hence ERC-2612.

**Comment by DMats** [comment]
We closed this issue because EIP-2612 has been implemented in our v4 contracts.

**Comment by TimDaub** [comment]
Cool ✌🏻 thanks
