### ISSUE TITLE
Release an alpha version of the Ocean Contracts to PyPi

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/contracts#348]
Version: 1.0.0-alpha1

**Comment by DMats** [comment]
Notes from today's Sprint Planning:

1. Use `twine` package creation commands to create PyPi package. See examples in from github release.tox action in Ocean.py.
2. Ask @alexcos20 for the PyPi credentials, when needed.
3. Release dev versions on both npm and PyPi.  Try to match the standard naming conventions for both.
4. The package version for both npm and PyPi should be `1.0.0-alpha1`

**Comment by DMats** [comment]
@alexcos20 @calina-c What should the package name be?

**Comment by DMats** [comment]
Nevermind.  I figured out that I should keep the existing package names on npm and PyPi.

**Comment by DMats** [comment]
Note to self, reference https://github.com/oceanprotocol/ocean.py/issues/392 for investigation of how to release dev versions on PyPi.

**Comment by DMats** [comment]
@alexcos20 @AnaLoznianu @calina-c I request approval to name the PyPi release `1.0.0a1` instead of `1.0.0-alpha1`
1. It adheres to [PEP 440#pre-releases](https://www.python.org/dev/peps/pep-0440/#pre-releases) (quoted below)
2. It would allow `pip` to parse the version number correctly. For reference, `pip` uses [packaging](https://packaging.pypa.io/en/latest/version.html) to parse version numbers.

>### Pre-releases
>Some projects use an "alpha, beta, release candidate" pre-release cycle to support testing by their users prior to a final release.
>
>If used as part of a project's development cycle, these pre-releases are indicated by including a pre-release segment in the >version identifier:
>
```
X.YaN   # Alpha release
X.YbN   # Beta release
X.YrcN  # Release Candidate
X.Y     # Final release
```

**Comment by DMats** [comment]
Tentative plan:
Once #350 is merged, I'll create a `1.0.0a1` release in Github which should trigger the python-publish workflow.

**Comment by alexcos20** [comment]
but is this compatible with npm ?
as far as I can tell, npm accepts "alpha, beta"

**Comment by kremalicious** [comment]
yeas this should all work on npm too. On npm we have tags similar to DockerHub has labels, on npm that is `latest` and usually `next` but tag can be anything. Tag then is not dependent on the version number or actual git tag which can include anything like David suggested. The trick is for npm to then link a pre-release version number/git tag with the respective npm tag which should be `next`.

In ocean.js this works quite well: https://github.com/oceanprotocol/ocean.js/blob/main/.github/workflows/publish.yml#L21-L27

**Comment by DMats** [comment]
Now that the NPM and PyPi release workflows have been added, I believe we should apply the `v1.0.0-alpha.1` version tag to the latest commit in the `v4main` branch.  

Once this occurs, we can remove the artifacts that have been copied to the ocena.py, provider, and aquarius repositories.

**Comment by DMats** [comment]
@AnaLoznianu @alexcos20 @calina-c 
At this point, we have a process in place for developing components (aquarius, provider) using local copies of the contract artifacts so an alpha release is not required.  Thus, I propose we close this issue.

**Comment by DMats** [comment]
@alexcos20 told me that he'd handle this issue.

**Comment by alexcos20** [comment]
done, see slack
