### ISSUE TITLE
cleanup/remove outdated docs

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/contracts#370]
When getting up to speed with v4 finding a `docs/` folder with a huge mix of v2/v3/v4 docs was really counterproductive. Please consolidate that into as less files as possible.

Like, why is this all there? Hard to tell what documents are actually worked against:

- overview.md
- parameters.md
- beginners_guide.md (this was especially confusing as this invites newcomers to look at it first)
- get-test-OCEAN.md (tells me to complete other "tutorials" first but links to non-existent files)
- quickstart_v3.md
- services.md
- wallets.md (why would we try to teach users about wallets in this repo?)

And multiple docs talk about setting up a Node.js project which I'm not sure this is a bit out of scope for this repo. But if we keep it installing packages is NOT done by manually adding packages to package.json but doing an `npm install PACKAGENAME`. So wherever we do this in docs, this needs to be updated too.

Finally all the image files scattered around the project root should not be there but live alongside the markdown files they are used, which I suppose should be `docs/`.

Another small thing is for whatever reason we tell people to use `npx` to run `hardhat` but then we install it in `devDependencies`. So why the `npx` usage then? `npx` freshly downloads the package EVERY TIME it is run, despite user having `hardhat` installed already. We do this in every npm script we run as it seems.

**Comment by akshay-ap** [comment]
Can I take this issue?

**Comment by AnaLoznianu** [comment]
@alexcos20 I see that Andrea added a PR for this with various changes. Can you please take a look please?

**Comment by alexcos20** [comment]
I will close that PR, cause it has a lot of old additional code for tests and open a new one containing just docs

**Comment by AnaLoznianu** [comment]
Thanks
