### ISSUE TITLE
Metadata validators

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/contracts#438]
When setiing metadata, add an optional array of proofs of validated metadata.  E

publisher may validate their SD (DDO) to a remote FederatedCatalogue(Aquarius), using a simple HTTP endpoint. FD validates the SD, and responds with :
- signature (v, r, s),
- FD_public_key
- FD_url
- hash (sha256) of data
when publishing on chain, setMetaData functions takes those parameters as well:
- if FD_public_key is not address_zero, performs ec_recover. If all well, emits the MetaData event (containing SD(DDO), hash, signature,FD_public_key, FD_URL). So anyone can see who validated that and also do ec_recover to double check.
- if FD_public_lkey is address_zero, no ec_recover was performed. -> MetaData event is emitted, but FD_public_key is address zero , so noboby validated the SD (your choice if you are going to use it or not)

**Comment by DMats** [comment]
@alexcos20 Out of curiosity, what does SD and FD stand for in your description above?
