### ISSUE TITLE
Update contract docs for v4

### ISSUE THREAD

**Issue by akshay-ap** [oceanprotocol/contracts#439]
**Is your feature request related to a problem? Please describe.**

- [x] Create a diagram and update REAMDE for v4 contracts.
Updated requirements:
- [x] Mention more template contract can be added in future.
- [x] Fix size of "Enterprise Datatoken contract" box
- [x] Mention name of smart contracts with each box

**Describe the solution you'd like**
NA

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by AnaLoznianu** [comment]
@akshay-ap We still need to do something on this issue or we can close it?
