### ISSUE TITLE
Vesting min blocks

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/contracts#446]
Right now, in order to setup vesting, you need at least 2426000 blocks of lock time  (~ 1 year).

https://github.com/oceanprotocol/contracts/blob/v4main_postaudit/contracts/templates/ERC20Template.sol#L301

I think we need a discussion about this.

@trentmc

**Comment by trangnv** [comment]
We can parametrize that value with tokenSpice, that's one thing I can try.

**Comment by alexcos20** [comment]
@trangnv - see PR pls

**Comment by trangnv** [comment]
I tried to deploy locally:
- ss_rate = Wei(0.1)
- DT_cap = 10000
- ss_DT_vest_amt = 1000.0
- init_liquidity = 90000.0
- Resulting spotPrice ~10

And the I got 
```console
>>> dt.balanceOf(pool.address)/1e18
9000.0
>>> dt.balanceOf(ss.address)/1e18
1000.0000000000003
```

**Comment by trangnv** [comment]
`updateMinVestingPeriod` can be called by Router owner, would that be a problem or there will be only 1 Router that exists and controlled by OPF?
