### ISSUE TITLE
Vesting & cap

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/contracts#447]
Looking at https://github.com/oceanprotocol/contracts/blob/v4main_postaudit/contracts/pools/ssContracts/SideStaking.sol#L319, I've found a bug.

Potential attack:
  - publisherA  creates an DT with a totalcap of 100 DT, sets vestingAmount = 10 , pool Spot Price = 1, base token = Ocean
  - creates the pool with initial liquidity  10 Ocean (and thus 10 DT added by SS)
  - malicious actor adds 90 Ocean (and thus 90DT are added by SS)
  - publisherA cannot get his vested amount, because we are reaching the cap in the previous step

Fix:  Make sure that we always have enough balance left for vesting when calling canStake

**Comment by lacoop6tu** [comment]
This scenario was already taken into account here:
https://github.com/oceanprotocol/contracts/blob/6bb30a25c707285412bda200783aa5729540b735/contracts/pools/ssContracts/SideStaking.sol#L116
and tested here:
https://github.com/oceanprotocol/contracts/blob/6bb30a25c707285412bda200783aa5729540b735/test/flow/SwapFees.test.js#L5222
