### ISSUE TITLE
Replace "dataToken" -> "datatoken" etc, everywhere

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/contracts#450]
**Is your feature request related to a problem? Please describe.**

It's not "data token". There is no space,  it's "datatoken"; It's a single word; there are several reasons for this. 

v3 wasn't filly consistent this way. Let's take the opportunity to make v4 consistent, before we ship the first version.

Searching for "datatoken" in the repo reveals "dataToken" in a few places. Searching "data token" reveals more. These need fixing.
https://github.com/oceanprotocol/contracts/search?q=datatoken

**Describe the solution you'd like**
Everywhere in ocean.py, replace:
- "dataToken" -> "datatoken"
- "DataToken" -> "Datatoken"
- "data token" -> "datatoken"
- "data_token" -> "datatoken"
- "Data Token" -> "Datatoken"
- etc

**Additional context**
A "datatoken" is the ERC20 fungible token. Complementary to it is the "Data NFT", an ERC721 non-fungible token. "Data NFT" _does_ have a space.

Related issues: [ocean.py](https://github.com/oceanprotocol/ocean.py/issues/651), [ocean.js](https://github.com/oceanprotocol/ocean.js/issues/1217)

**Comment by AnaLoznianu** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Backend-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/contracts/450?planning-poker) with ZenHub @lacoop6tu

**Comment by alexcos20** [comment]
Make sure that baseToken remains unchanged
