### ISSUE TITLE
BPool size

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/contracts#490]
Currently, the compiled version of BPool is 24.548 Kb, which is very close to the limit.  We might not be able to deploy on mainnet.
Also, if #487 needs additional code, it's not possible.

On single side join/exit we have the following one side stake/unstake functions:
- joinswapExternAmountIn - add liquidity to get at least minPoolAmountOut by spending an exact amount of tokenAmountIn tokens (IE: I want to add 100 OCEAN to the pool and get at least 10 pool shares)
- joinswapPoolAmountOut - add liquidity to get exact `poolAmountOut` shares by spending at most maxAmountIn of tokenIn  (IE: I want to get 100 pool shares and I'm willing to spend at most 100 OCEAN)
- exitswapPoolAmountIn - spends exact poolAmountIn shares to get minimum minAmountOut of tokenOUT (ie: you want to unstake 100 pool shares to get at least 10 OCEAN)
- exitswapExternAmountOut  - spends at most maxPoolAmountIn shares to get exact tokenAmountOut of tokenOut  (ie: you want to unstake an exact number of OCEAN and you are willing to spend at most X pool shares)

I think we can delete:
   -  joinswapPoolAmountOut  (you can do the math and call joinswapExternAmountIn if you want to get exact 100 shares)
   - exitswapExternAmountOut  (you can do math if you want to get exact 100 OCEAN out of the pool)

Why keep:
 - joinswapExternAmountIn  - usually a staker has 100 OCEAN tokens in his wallet, doesn't really matter how much pool shares he will get
 - exitswapPoolAmountIn - staker has pool shares in his wallet, and on unstake he knows how much LP he want to spend

thoughts?
@trentmc @kremalicious @mihaisc

**Comment by trentmc** [comment]
This proposal is ok by me.

**Comment by mihaisc** [comment]
agree, user doesn't interact directly with pool shares
