### ISSUE TITLE
Wrong param description

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/contracts#573]
https://github.com/oceanprotocol/contracts/blob/5bc6ca0189259e18863543abff6f25c55f2db5e3/contracts/ERC721Factory.sol#L301
Should be paymentCollector , see https://github.com/oceanprotocol/contracts/blob/6907a7e7a5bfb215ba5bdf96e8fab75c6bd4a60c/contracts/templates/ERC20Template.sol#L250

**Comment by alexcos20** [comment]
fixed in https://github.com/oceanprotocol/contracts/pull/556/commits/c356d9957a1ad311bdf4d16943ff8a33b29b7fe7
