### ISSUE TITLE
Incorrect parameter comment for ERC721Template.sol createERC20 method

### ISSUE THREAD

**Issue by soonhuat** [oceanprotocol/contracts#593]
**Describe the bug**
Amend createERC20 parameter comment as below, because are use as paymentCollector in all the underlying method.

from: [1]  = feeManager initial feeManager for this DT
to: [1]  = paymentCollector  initial paymentCollector  for this DT

**Screenshots**
<img width="1376" alt="image" src="https://user-images.githubusercontent.com/7642607/160338226-f1acbe52-3e10-4e06-85ff-9d5269eb0ec2.png">

Both of the below underlying method are using it as paymentCollector 
https://github.com/oceanprotocol/contracts/blob/585a8a560888a383ad6453a1098c090110d6d6fe/contracts/ERC721Factory.sol#L301
and here
https://github.com/oceanprotocol/contracts/blob/585a8a560888a383ad6453a1098c090110d6d6fe/contracts/templates/ERC20TemplateEnterprise.sol#L242

**Additional context**
Unfortunately I doesn't have the access to direct create a PR for this.

**Comment by alexcos20** [comment]
See v4main branch:

https://github.com/oceanprotocol/contracts/blob/v4main/contracts/templates/ERC20TemplateEnterprise.sol#L242
and
https://github.com/oceanprotocol/contracts/blob/v4main/contracts/ERC721Factory.sol#L301

**Comment by soonhuat** [comment]
@alexcos20 
the line that wrong are this
[****](https://github.com/oceanprotocol/contracts/blob/585a8a560888a383ad6453a1098c090110d6d6fe/contracts/templates/ERC721Template.sol#L338)
