### ISSUE TITLE
FixedRate:  getBTSupply fails if basetoken contract does not exists

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/contracts#718]
https://github.com/oceanprotocol/contracts/blob/main/contracts/pools/fixedRate/FixedRateExchange.sol#L862

Test:  https://goerli.etherscan.io/address/0xc313e19146fc9a04470689c9d41a4d3054693531#readContract  and use 0xCBFDAC464E43F9EC83EB74CFE5C2E72B00B9CD869F473818578BDC0DDE2611B0  as exchangeID

Exchange was created in https://goerli.etherscan.io/tx/0xce43ff6a01a90471e988fedd4bf01e87e24803c3ae62ec8713b3b8371eb00246#eventlog

**Comment by mihaisc** [comment]
@alexcos20 status?
