### ISSUE TITLE
Wrong smart contracts used by ocean bridge multichain. Coins lost in space forever ?

### ISSUE THREAD

**Issue by bluetyphoon77** [oceanprotocol/contracts#735]
Hi dear devs,
I reach to you because I bridged my 500 OCEAN from ETH chain (https://etherscan.io/address/0x36B5B58C27Bb3bF9e612D97504DC8909172dBBfa#tokentxns)  to BSC chain with Multichain. 
(https://bscscan.com/tx/0xcbf3f794a9fab73fd99998b7394fd45c84c314823eaa5b05e112094135ff097b)
I then sent them directly to Binance BSC OCEAN adress. 
https://bscscan.com/tx/0x2e75350efe5a59ff863f93f12776b533684b777f843b594297d076538942c38a
They never arrived. Binance told me the smart contract for the OCEAN coin is wrong and not the one used by binance. 
What did really happen ? Why is the smart contract wrong ? Do you audit them before letting bridges use them ?
Thanks alot for any help, it could avoid all the OCEAN community to have those problems.
Y.

**Comment by mihaisc** [comment]
this issue was resolved on discord
