### ISSUE TITLE
Automate veFeeDistributor checkpoints

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/contracts#747]
Due to veFeeDistributor design, we need to call checkpoint_token and checkpoint_total_supply every Thu, after 00:00.

We can do it with Gelato, but there is a caveat:  Only owner is guaranteed to have success on those calls, for other addresses it may fail and rewards can fail.

Status quo:  there is a multisig that owns veFeeDistributor, we generate tx from df-py and somebody signs them and executes them.

Proposal:
 - write a contract that owns veFeeDistributor and it's owned by multisig (veFeeOwner.sol)
 - write a gelato cron to automate checkpoint_token and checkpoint_total_supply
 - remove code from df-py

**Comment by mihaisc** [comment]
@alexcos20 is this still relevant?
