### ISSUE TITLE
Document templates

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/contracts#754]
### Background / motivation

[This comment in ocean.py](https://github.com/oceanprotocol/ocean.py/issues/1315#issuecomment-1432848930) describes differences between DT1 & DT2, and for future extensibility & maintenance , a table would help a lot.

Now we're doing DT3 - the first predictoor DT template. [This comment in contracts](https://github.com/oceanprotocol/contracts/pull/749#discussion_r1192889695) describes how the table would help for this.

So, time to do the table! :)

### TODO

- [ ] Add README in contracts/templates and describe each template
- [ ] Link to the new README from top-level README

**Comment by mihaisc** [comment]
we should do this, even if it's just basic information
