### ISSUE TITLE
FRE2.0:  Remove owner transfer of baseTokens on sellDT

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/contracts#773]
see https://github.com/oceanprotocol/privateissues/issues/74

To Do:

- [X] Update contract
- [x] Update tests

**Comment by mihaisc** [comment]
@alexcos20 status on this?

**Comment by alexcos20** [comment]
closing this, since tests were added:  https://github.com/oceanprotocol/contracts/blob/v2.0/test/flow/FixedRateExchange.test.js#L4346
