### ISSUE TITLE
[predictoor] Expose agg predval after epoch closes and emit the values within submit trueval

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/contracts#795]
### Summary

Expose agg predval after epoch closes and emit the values within submit trueval function

### Context

(From slack:  [Msg 1](https://oceanprotocol.slack.com/archives/C054ZHZ11RU/p1692126865179389), [Msg 2 - n](https://oceanprotocol.slack.com/archives/C054ZHZ11RU/p1692127194652489))

Roberto: I assumed that aggPredval was exposed after the epoch ends, and it is, but not only until the first user claims. There were some discussions/concerns around data devaluation, as we're exposing this value after the epoch ending, without users paying for it.

Trent: to be clear, the agg predval gets exposed after its counterpart trueval comes available. Correct? If yes, that is the intended behavior

Berkay: Not the case at the moment, contract still checks for subscription. I don't see a reason not to expose it, contract exposes all predictions after the epoch closes, we might as well expose the aggpredval, should be fine.

Trent: Yes, please change it like you say, Berkay. Create a ticket etc to track

Roberto: Thank you, this is great. I think it's super important for us to be able to report accuracy and "show all the cards" at the same time. I'll be looking at the contract more to see if there are more hidden gems. 

Alex: [here's the PR] https://github.com/oceanprotocol/contracts/pull/796

**Comment by trentmc** [comment]
> [Roberto] Here are the desired params we would like to see in TruevalSubmitted event.
> .... startValue ... endValue ...

FWIW this request is outside the scope of _this_ issue. And it's not needed, as discussed in slack. I will summarize below. 

For reference, here is the status quo of what's emitted. [Ref: ERC20Template3.sol in contracts v2 branch](https://github.com/oceanprotocol/contracts/blob/870c4b852b7972cfbcf7f61e0414260283d2f7c2/contracts/templates/ERC20Template3.sol#L74):
```text
    event TruevalSubmitted(
        uint256 indexed slot,
        bool trueValue,
        uint256 floatValue,
        Status status,
        uint256 roundSumStakesUp,
        uint256 ### roundSumStakes
    );
```

> [Roberto] Here are the desired params we would like to see in TruevalSubmitted event.
> ..
> ..  uint256 startValue,
> ..  uint256 endValue,

> [Trent, in slack](https://oceanprotocol.slack.com/archives/C051UV3J3T4/p1692177182026479?thread_ts=1690934740.321649&cid=C051UV3J3T4) It's already here. Nothing to implement.

> [Alex, in slack](https://oceanprotocol.slack.com/archives/C051UV3J3T4/p1692200625694869?thread_ts=1690934740.321649&cid=C051UV3J3T4) You don't need that.
> Because candle_end_epoch_i = candle_open_epoch_i+1
> So you can get endValue for epoch X and compare it to endValue for epoch X-1
