### ISSUE TITLE
DFRewards.sol:  Add support for native tokens

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/contracts#813]
DFRewards should support native tokens (ie: ETH), along with ERC20.

Proposal:
 - for claim functions, if token address = 0x000, then it refers to ETH
 - add another function "allocateETH" that checks msg.value and distributes ETH among addresses

**Comment by trentmc** [comment]
Why do we need this? 

Can't it just be a script that sends the ROSE? We shouldn't need to change smart contracts.

**Comment by trentmc** [comment]
Once again: why do we need this. Just run a script, send $ROSE. No smart contract needed.

**Comment by trentmc** [comment]
But we don't do that for Predictoor DF. Why would we do it here?

**Comment by alexcos20** [comment]
Because sending ROSE to 100 addresses will take around 1000 seconds...  DF-py github actions most likely will crush.  Unless we do it manually with a script, and not automated

**Comment by alexcos20** [comment]
Solved, we have wrapped ROSE  (https://docs.oasis.io/dapp/sapphire/addresses)
